TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitUtils
    DataTransferKitInterface
    DataTransferKitOperators
    DataTransferKitIntrepidAdapters
    Teuchos 
    Tpetra
    Shards
    Intrepid
    STKUtil
    STKTopology
    STKMesh
  TEST_REQUIRED_PACKAGES
    STKIO
  LIB_REQUIRED_TPLS
    MPI
  )
