TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitUtils
    DataTransferKitInterface
    DataTransferKitOperators
    DataTransferKitBasicGeometryAdapters
    DataTransferKitIntrepidAdapters
    Teuchos
    Tpetra
  LIB_REQUIRED_TPLS
    MPI
  )