! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module datatransferkit
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 public :: DTK_version
 public :: DTK_git_commit_hash
 ! typedef enum DTK_CellTopology
 enum, bind(c)
  enumerator :: DTK_TRI_3 = 0
  enumerator :: DTK_TRI_6
  enumerator :: DTK_QUAD_4
  enumerator :: DTK_QUAD_9
  enumerator :: DTK_TET_4
  enumerator :: DTK_TET_10
  enumerator :: DTK_TET_11
  enumerator :: DTK_HEX_8
  enumerator :: DTK_HEX_20
  enumerator :: DTK_HEX_27
  enumerator :: DTK_PYRAMID_5
  enumerator :: DTK_PYRAMID_13
  enumerator :: DTK_WEDGE_6
  enumerator :: DTK_WEDGE_15
  enumerator :: DTK_WEDGE_18
  enumerator :: DTK_N_TOPO
 end enum
 integer, parameter, public :: DTK_CellTopology = kind(DTK_TRI_3)
 public :: DTK_TRI_3, DTK_TRI_6, DTK_QUAD_4, DTK_QUAD_9, DTK_TET_4, DTK_TET_10, DTK_TET_11, DTK_HEX_8, DTK_HEX_20, DTK_HEX_27, &
    DTK_PYRAMID_5, DTK_PYRAMID_13, DTK_WEDGE_6, DTK_WEDGE_15, DTK_WEDGE_18, DTK_N_TOPO
 public :: DTK_initialize

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_int
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_p_p_char
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: DTK_initialize_cmd
 public :: DTK_is_initialized
 public :: DTK_finalize
 ! typedef enum DTK_Error
 enum, bind(c)
  enumerator :: DTK_SUCCESS = 0
  enumerator :: DTK_INVALID_HANDLE = -1
  enumerator :: DTK_UNINITIALIZED = -2
  enumerator :: DTK_UNKNOWN = -99
 end enum
 integer, parameter, public :: DTK_Error = kind(DTK_SUCCESS)
 public :: DTK_SUCCESS, DTK_INVALID_HANDLE, DTK_UNINITIALIZED, DTK_UNKNOWN
 ! typedef enum DTK_MemorySpace
 enum, bind(c)
  enumerator :: DTK_HOST_SPACE
  enumerator :: DTK_CUDAUVM_SPACE
 end enum
 integer, parameter, public :: DTK_MemorySpace = kind(DTK_HOST_SPACE)
 public :: DTK_HOST_SPACE, DTK_CUDAUVM_SPACE
 ! typedef enum DTK_ExecutionSpace
 enum, bind(c)
  enumerator :: DTK_SERIAL
  enumerator :: DTK_OPENMP
  enumerator :: DTK_CUDA
 end enum
 integer, parameter, public :: DTK_ExecutionSpace = kind(DTK_SERIAL)
 public :: DTK_SERIAL, DTK_OPENMP, DTK_CUDA
 public :: DTK_create_user_application
 public :: DTK_is_valid_user_application
 public :: DTK_destroy_user_application
 ! typedef enum DTK_FunctionType
 enum, bind(c)
  enumerator :: DTK_NODE_LIST_SIZE_FUNCTION
  enumerator :: DTK_NODE_LIST_DATA_FUNCTION
  enumerator :: DTK_BOUNDING_VOLUME_LIST_SIZE_FUNCTION
  enumerator :: DTK_BOUNDING_VOLUME_LIST_DATA_FUNCTION
  enumerator :: DTK_POLYHEDRON_LIST_SIZE_FUNCTION
  enumerator :: DTK_POLYHEDRON_LIST_DATA_FUNCTION
  enumerator :: DTK_CELL_LIST_SIZE_FUNCTION
  enumerator :: DTK_CELL_LIST_DATA_FUNCTION
  enumerator :: DTK_BOUNDARY_SIZE_FUNCTION
  enumerator :: DTK_BOUNDARY_DATA_FUNCTION
  enumerator :: DTK_ADJACENCY_LIST_SIZE_FUNCTION
  enumerator :: DTK_ADJACENCY_LIST_DATA_FUNCTION
  enumerator :: DTK_DOF_MAP_SIZE_FUNCTION
  enumerator :: DTK_DOF_MAP_DATA_FUNCTION
  enumerator :: DTK_MIXED_TOPOLOGY_DOF_MAP_SIZE_FUNCTION
  enumerator :: DTK_MIXED_TOPOLOGY_DOF_MAP_DATA_FUNCTION
  enumerator :: DTK_FIELD_SIZE_FUNCTION
  enumerator :: DTK_PULL_FIELD_DATA_FUNCTION
  enumerator :: DTK_PUSH_FIELD_DATA_FUNCTION
  enumerator :: DTK_EVALUATE_FIELD_FUNCTION
 end enum
 integer, parameter, public :: DTK_FunctionType = kind(DTK_NODE_LIST_SIZE_FUNCTION)
 public :: DTK_NODE_LIST_SIZE_FUNCTION, DTK_NODE_LIST_DATA_FUNCTION, DTK_BOUNDING_VOLUME_LIST_SIZE_FUNCTION, &
    DTK_BOUNDING_VOLUME_LIST_DATA_FUNCTION, DTK_POLYHEDRON_LIST_SIZE_FUNCTION, DTK_POLYHEDRON_LIST_DATA_FUNCTION, &
    DTK_CELL_LIST_SIZE_FUNCTION, DTK_CELL_LIST_DATA_FUNCTION, DTK_BOUNDARY_SIZE_FUNCTION, DTK_BOUNDARY_DATA_FUNCTION, &
    DTK_ADJACENCY_LIST_SIZE_FUNCTION, DTK_ADJACENCY_LIST_DATA_FUNCTION, DTK_DOF_MAP_SIZE_FUNCTION, DTK_DOF_MAP_DATA_FUNCTION, &
    DTK_MIXED_TOPOLOGY_DOF_MAP_SIZE_FUNCTION, DTK_MIXED_TOPOLOGY_DOF_MAP_DATA_FUNCTION, DTK_FIELD_SIZE_FUNCTION, &
    DTK_PULL_FIELD_DATA_FUNCTION, DTK_PUSH_FIELD_DATA_FUNCTION, DTK_EVALUATE_FIELD_FUNCTION
 public :: DTK_set_user_function

! WRAPPER DECLARATIONS
interface
 subroutine SWIG_free(cptr) &
  bind(C, name="free")
 use, intrinsic :: ISO_C_BINDING
 type(C_PTR), value :: cptr
end subroutine
function swigc_DTK_version() &
bind(C, name="_wrap_DTK_version") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: fresult
end function

function swigc_DTK_git_commit_hash() &
bind(C, name="_wrap_DTK_git_commit_hash") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_DTK_initialize() &
bind(C, name="_wrap_DTK_initialize")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine swigc_DTK_initialize_cmd(farg1, farg2) &
bind(C, name="_wrap_DTK_initialize_cmd")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_DTK_is_initialized() &
bind(C, name="_wrap_DTK_is_initialized") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

subroutine swigc_DTK_finalize() &
bind(C, name="_wrap_DTK_finalize")
use, intrinsic :: ISO_C_BINDING
end subroutine

function swigc_DTK_create_user_application(farg1) &
bind(C, name="_wrap_DTK_create_user_application") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_DTK_is_valid_user_application(farg1) &
bind(C, name="_wrap_DTK_is_valid_user_application") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_DTK_destroy_user_application(farg1) &
bind(C, name="_wrap_DTK_destroy_user_application")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: farg1
end subroutine

subroutine swigc_DTK_set_user_function(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_DTK_set_user_function")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_FUNPTR), value :: farg3
type(C_PTR), intent(in) :: farg4
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS

subroutine SWIGTM_fout_char_Sm_(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(in) :: imout
  character(len=:), allocatable, intent(out) :: fout
  character(kind=C_CHAR), dimension(:), pointer :: chars
  integer(kind=C_SIZE_T) :: i
  call c_f_pointer(imout%data, chars, [imout%size])
  allocate(character(len=imout%size) :: fout)
  do i=1, imout%size
    fout(i:i) = char(ichar(chars(i)))
  end do
end subroutine

function DTK_version() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(len=:), allocatable :: swig_result
type(SwigArrayWrapper) :: fresult 

fresult = swigc_DTK_version()
call SWIGTM_fout_char_Sm_(fresult, swig_result)
call SWIG_free(fresult%data)
end function

function DTK_git_commit_hash() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(len=:), allocatable :: swig_result
type(SwigArrayWrapper) :: fresult 

fresult = swigc_DTK_git_commit_hash()
call SWIGTM_fout_char_Sm_(fresult, swig_result)
call SWIG_free(fresult%data)
end function

subroutine DTK_initialize()
use, intrinsic :: ISO_C_BINDING

call swigc_DTK_initialize()
end subroutine

subroutine DTK_initialize_cmd(argc, argv)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_int), intent(in) :: argc
class(SWIGTYPE_p_p_p_char), intent(in) :: argv
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = argc%swigdata
farg2 = argv%swigdata
call swigc_DTK_initialize_cmd(farg1, farg2)
end subroutine


subroutine SWIGTM_fout_bool(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  integer(kind=C_INT), intent(in) :: imout
  logical, intent(out) :: fout
  ! TODO: fout = (imout /= 0) ???
  if (imout /= 0) then
    fout = .true.
  else
    fout = .false.
  end if
end subroutine

function DTK_is_initialized() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_DTK_is_initialized()
call SWIGTM_fout_bool(fresult, swig_result)
end function

subroutine DTK_finalize()
use, intrinsic :: ISO_C_BINDING

call swigc_DTK_finalize()
end subroutine

function DTK_create_user_application(space) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
integer(DTK_MemorySpace), intent(in) :: space
type(C_PTR) :: fresult 
integer(C_INT) :: farg1 

farg1 = space
fresult = swigc_DTK_create_user_application(farg1)
swig_result = fresult
end function

function DTK_is_valid_user_application(handle) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
type(C_PTR), intent(in) :: handle
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = handle
fresult = swigc_DTK_is_valid_user_application(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

subroutine DTK_destroy_user_application(handle)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handle
type(C_PTR) :: farg1 

farg1 = handle
call swigc_DTK_destroy_user_application(farg1)
end subroutine

subroutine DTK_set_user_function(handle, type, f, user_data)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handle
integer(DTK_FunctionType), intent(in) :: type
type(C_FUNPTR), intent(in), value :: f
type(C_PTR), intent(in) :: user_data
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 
type(C_FUNPTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = handle
farg2 = type
farg3 = f
farg4 = user_data
call swigc_DTK_set_user_function(farg1, farg2, farg3, farg4)
end subroutine


end module
