variables:
  CI_DEBUG_SERVICES: "trace"
  SCHEDULER_PARAMETERS: "-P GEN007CITEST -J qdi_test -nnodes 1 -W 0:30 -nnodes 1"
  TRILINOS_DIR: "/ccsopen/home/qdi/Workspace/Trilinos"
  BENCHMARK_ROOT: "/ccsopen/home/qdi/Workspace/opt/benchmark"

stages:
  - build
  - test

BuildDataTransferKit:
  stage: build
  script:
    - sh -xe ./docker/gitlab/build.sh
  tags:
    - nobatch
  artifacts:
    paths:
      - build/

TestDataTransferKit:
  stage: test
  script:
    - module restore dtk && cd build && ctest --output-on-failure
  tags:
    - batch
  dependencies:
    - BuildDataTransferKit
