sudo: required

services:
  - docker

notifications:
  email: false

before_install:
  - docker pull dalg24/dtk-stack
  - docker run
        --detach --tty
        --name=test-machine
        --volume ${TRAVIS_BUILD_DIR}:/scratch/source/dtk
        --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
        --env CTEST_BUILD_NAME="$(curl -s https://raw.githubusercontent.com/ORNL-CEES/Cap/master/docker/get_build_info.sh | bash)"
        dalg24/dtk-stack
  - docker ps -a
  - env
  - docker exec test-machine
        /scratch/source/dtk/docker/build_dtk_and_run_unit_tests.sh

script:
  - echo "Hello World"
