SET(Coupler_VERSION 0.0.1)
SET(Coupler_MAJOR_VERSION 0)
SET(Coupler_MAJOR_MINOR_VERSION 000001)
SET(Coupler_VERSION_STRING "0.0.1 (Dev)")
SET(Coupler_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
