SET(DataTransferKit_VERSION 2.0.0)
SET(DataTransferKit_MAJOR_VERSION 2)
SET(DataTransferKit_MAJOR_MINOR_VERSION 020000)
SET(DataTransferKit_VERSION_STRING "2.0.0")
SET(DataTransferKit_ENABLE_DEVELOPMENT_MODE_DEFAULT OFF) # Change to 'OFF' for a release
