SET(LIB_REQUIRED_DEP_PACKAGES
  DataTransferKitNanoflann
  DataTransferKitUtils
  Teuchos 
  Tpetra
  AztecOO
  Belos
  ThyraCore
  ThyraTpetraWrappers
  Stratimikos
 )

SET(LIB_OPTIONAL_DEP_PACKAGES)

SET(TEST_REQUIRED_DEP_PACKAGES
  DataTransferKitBasicGeometryAdapters
)

SET(TEST_OPTIONAL_DEP_PACKAGES)

SET(LIB_REQUIRED_DEP_TPLS)

SET(LIB_OPTIONAL_DEP_TPLS)

SET(TEST_REQUIRED_DEP_TPLS)

SET(TEST_OPTIONAL_DEP_TPLS)
