TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitNanoflann
    DataTransferKitUtils
    Teuchos 
    Tpetra
    AztecOO
    Belos
    ThyraCore
    ThyraTpetraAdapters
    Stratimikos
  TEST_REQUIRED_PACKAGES
    DataTransferKitBasicGeometryAdapters
  )
