#!/bin/bash

if [ $TRILINOS_HOME ]; then
  echo "TRILINOS_HOME has already been set!"
else
  echo "TRILINOS_HOME has not been set.  Setting it!"
  export TRILINOS_HOME=`pwd`/../../../Trilinos/
fi

echo
echo "Generating doxygen browser documentation for all of DataTransferKit as a single doxygen collection ..."
echo

doxygen ../browser/doc/Doxyfile

echo
echo "Generating main DataTransferKit doxygen documentation pages ..."
echo

doxygen Doxyfile
