set(CTEST_PROJECT_NAME "DataTransferKit")
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")

set(CTEST_SOURCE_DIRECTORY "$ENV{PREFIX}/source/trilinos/12.4.2")
set(CTEST_BINARY_DIRECTORY "$ENV{PREFIX}/build/trilinos/12.4.2")

set(CMAKE_EXTRA_ARGS "")
set(CMAKE_EXTRA_ARGS "${CMAKE_EXTRA_ARGS} -D Trilinos_EXTRA_REPOSITORIES=DataTransferKit")
set(CMAKE_EXTRA_ARGS "${CMAKE_EXTRA_ARGS} -D Trilinos_ENABLE_DataTransferKit=ON")
set(CMAKE_EXTRA_ARGS "${CMAKE_EXTRA_ARGS} -D DataTransferKit_ENABLE_DBC=ON")
set(CMAKE_EXTRA_ARGS "${CMAKE_EXTRA_ARGS} -D DataTransferKit_ENABLE_TESTS=ON")
set(CTEST_CONFIGURE_COMMAND "$ENV{PREFIX}/source/dtk/docker/configure_trilinos.sh ${CMAKE_EXTRA_ARGS}")

set(CTEST_SITE "travis-ci")
set(CTEST_BUILD_NAME "$ENV{CTEST_BUILD_NAME}")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "jupyterdocker.ornl.gov/CDash")
set(CTEST_DROP_LOCATION "/submit.php?project=DataTransferKit")
set(CTEST_DROP_SITE_CDASH TRUE)

if("$ENV{TRAVIS_PULL_REQUEST}" MATCHES "false") 
    ctest_start("Continuous")
else()
    ctest_start("Experimental")
endif()
ctest_configure()
ctest_build()
ctest_test()
ctest_submit()
