from ubuntu:16.04

RUN apt-get update && apt-get install -y wget git python-sphinx doxygen && \
    echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main" > /etc/apt/sources.list.d/llvm.list && \
    wget -q -O - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    apt-get update && apt-get install -y clang-format-3.9 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

