from ubuntu:16.04

RUN apt-get update && apt-get install -y wget git python-pip doxygen && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir sphinx==1.4 breathe==4.6 && \
    echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main" > /etc/apt/sources.list.d/llvm.list && \
    wget -q -O - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    apt-get update && apt-get install -y clang-format-4.0 clang-tidy-4.0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

