TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitNanoflann
    DataTransferKitUtils
    DataTransferKitInterface
    Teuchos
    Tpetra
    ThyraCore
    ThyraTpetraAdapters
  TEST_REQUIRED_PACKAGES
    DataTransferKitBasicGeometryAdapters
  )
