TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitUtils
    DataTransferKitInterface
    Teuchos 
    Tpetra
  TEST_REQUIRED_PACKAGES
    DataTransferKitOperators
  LIB_REQUIRED_TPLS
    MPI
    Moab
  )
