#!/bin/bash
EXTRA_ARGS=$@
BLAS_DIR=/soft/libraries/alcf/20130312/gcc/BLAS
LAPACK_DIR=/soft/libraries/alcf/20130312/gcc/LAPACK
BOOST_DIR=/soft/libraries/boost/1.58.0/cnk-gcc/V1R2M2-20150523
ARGS=(
    -D CMAKE_BUILD_TYPE=Release
    -D BUILD_SHARED_LIBS=OFF
    -D TPL_FIND_SHARED_LIBS=OFF
    ### SETUP TO RUN MPI TESTS ###
    -D MPI_EXEC=runjob
    -D MPI_EXEC_NUMPROCS_FLAG="--np"
    -D MPI_EXEC_PRE_NUMPROCS_FLAGS=""
    -D MPI_EXEC_POST_NUMPROCS_FLAGS="-p;1;--block;\$ENV{COBALT_PARTNAME};--verbose=INFO;:"
    ### TPLs ###
    -D TPL_ENABLE_MPI=ON
    -D TPL_ENABLE_BLAS=ON
        -D BLAS_LIBRARY_DIRS=$BLAS_DIR/lib
    -D TPL_ENABLE_LAPACK=ON
        -D LAPACK_LIBRARY_DIRS=$LAPACK_DIR/lib
    -D TPL_ENABLE_Boost=ON
        -D Boost_INCLUDE_DIRS=$BOOST_DIR/include
        -D Boost_LIBRARY_DIRS=$BOOST_DIR/lib
    -D TPL_ENABLE_BoostLib=ON
        -D BoostLib_INCLUDE_DIRS=$BOOST_DIR/include
        -D BoostLib_LIBRARY_DIRS=$BOOST_DIR/lib
    -D TPL_ENABLE_MOAB=OFF
    -D TPL_ENABLE_Libmesh=OFF
    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF
    -D Trilinos_ENABLE_Tpetra=ON
    ### DTK ###
    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit"
    -D Trilinos_ENABLE_DataTransferKit=ON
        -D DataTransferKit_ENABLE_DBC=ON
        -D DataTransferKit_ENABLE_TESTS=ON
        -D DataTransferKit_ENABLE_EXAMPLES=OFF
    )
cmake "${ARGS[@]}" $EXTRA_ARGS $TRILINOS_DIR
