#!/bin/bash
EXTRA_ARGS=$@

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPT_DIR}/set_kokkos_env.sh

CUDA_NVCC_FLAGS="-arch=${GPU_ARCH};--expt-extended-lambda"

CUDA_ARGS=(
    -D TPL_ENABLE_CUDA=ON
    -D Kokkos_ENABLE_Cuda=ON
    -D Kokkos_ENABLE_Cuda_UVM=ON
    -D Kokkos_ENABLE_Cuda_Lambda=ON
    -D Tpetra_INST_CUDA=ON
)

${SCRIPT_DIR}/docker_cmake "${CUDA_ARGS[@]}" -D CUDA_NVCC_FLAGS="${CUDA_NVCC_FLAGS}" $EXTRA_ARGS
