#!/bin/bash
rm -f  CMakeCache.txt
rm -rf CMakeFiles/
EXTRA_ARGS=("$@")
ARGS=(
    -D CMAKE_BUILD_TYPE=Debug
    -D BUILD_SHARED_LIBS=ON
    ### COMPILERS AND FLAGS ###
#    -D CMAKE_CXX_FLAGS="-Wall -Wpedantic"
    -D DataTransferKit_CXX_FLAGS="-Wall -Wshadow -Wpedantic ${SANITIZER_FLAGS}"
    -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=ON
    ### TPLs ###
    -D TPL_ENABLE_MPI=ON
    -D TPL_ENABLE_BLAS=ON
    -D TPL_ENABLE_LAPACK=ON
    -D TPL_ENABLE_Boost=ON
        -D Boost_INCLUDE_DIRS=$BOOST_DIR/include
        -D Boost_LIBRARY_DIRS=$BOOST_DIR/lib
    -D TPL_ENABLE_Netcdf=ON
        -D Netcdf_INCLUDE_DIRS=$NETCDF_DIR/include
        -D Netcdf_LIBRARY_DIRS=$NETCDF_DIR/lib
    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF
    -D Trilinos_ENABLE_OpenMP=ON
    -D Trilinos_ENABLE_Tpetra=ON
        -D Tpetra_INST_INT_UNSIGNED_LONG=ON
        -D Tpetra_INST_COMPLEX_DOUBLE=OFF
        -D Tpetra_INST_COMPLEX_FLOAT=OFF
        -D Tpetra_INST_SERIAL=ON
        -D Tpetra_INST_OPENMP=ON
#    -D Kokkos_ENABLE_Serial=ON
    -D Kokkos_ENABLE_OpenMP=ON
    ### DTK ###
    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit"
    -D Trilinos_ENABLE_DataTransferKit=ON
        -D DataTransferKit_ENABLE_DBC=ON
        -D DataTransferKit_ENABLE_TESTS=ON
        -D DataTransferKit_ENABLE_EXAMPLES=ON
        -D DataTransferKit_ENABLE_ClangFormat=ON
    )
cmake "${ARGS[@]}" "${EXTRA_ARGS[@]}" $TRILINOS_DIR
