#!/bin/bash
EXTRA_ARGS=$@

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPT_DIR}/set_kokkos_env.sh

export CUDA_CXX_FLAGS="-g -arch=${GPU_ARCH} -lineinfo \
    -std=c++11 --expt-extended-lambda \
    -Xcudafe --diag_suppress=conversion_function_not_usable \
    -Xcudafe --diag_suppress=cc_clobber_ignored \
    -Xcudafe --diag_suppress=code_is_unreachable"

CUDA_ARGS=(
    -D TPL_ENABLE_CUDA=ON
    -D Kokkos_ENABLE_Cuda=ON
    -D Kokkos_ENABLE_Cuda_UVM=ON
    -D Kokkos_ENABLE_Cuda_Lambda=ON
    -D Tpetra_INST_CUDA=ON
)

${SCRIPT_DIR}/docker_cmake "${CUDA_ARGS[@]}" $EXTRA_ARGS
