#!/bin/bash
##---------------------------------------------------------------------------##
## CONFIGURE DTK
##---------------------------------------------------------------------------##

# This script will build DTK with Kokkos support for Serial, OpenMP, and CUDA
# node types.

# NOTE: The CUDA hardware architecture should be set in CMAKE_CXX_FLAGS. The
#       current flag setting is for compute capability 3.0. Change for your
#       architecture.

# NOTE: Before running this you must source set_kokkos_env.sh to set the NVCC
#       wrapper as the MPI C++ compiler implementation and your C++ compiler
#       as the NVCC compiler implementation. It will also set CUDA calls as 
#       blocking.
#
#       https://trilinos.org/about/documentation/building-with-cuda-support/

rm -rf CMakeCache.txt
rm -rf CMakeFiles

##---------------------------------------------------------------------------##

cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=/home/uy7/install/DataTransferKit/kokkos \
    -D CMAKE_BUILD_TYPE:STRING=DEBUG \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D BUILD_SHARED_LIBS:BOOL=OFF \
    -D CMAKE_CXX_COMPILER=/usr/bin/mpicxx \
    -D CMAKE_C_COMPILER=/usr/bin/mpicc \
    -D CMAKE_Fortran_COMPILER=/usr/bin/mpif90 \
    -D CMAKE_CXX_FLAGS="-g -arch=sm_30 -lineinfo \
-Xcudafe --diag_suppress=conversion_function_not_usable \
-Xcudafe --diag_suppress=cc_clobber_ignored \
-Xcudafe --diag_suppress=code_is_unreachable" \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D Boost_LIBRARY_DIRS:PATH=/home/uy7/install/boost_1_59_0/lib \
    -D Boost_INCLUDE_DIRS:PATH=/home/uy7/install/boost_1_59_0/include \
    -D BLAS_LIBRARY_DIRS:PATH=/home/uy7/install/lapack-3.5.0/lib \
    -D LAPACK_LIBRARY_DIRS:PATH=/home/uy7/install/lapack-3.5.0/lib \
    -D TPL_ENABLE_BinUtils:BOOL=ON \
    -D TPL_ENABLE_CUDA:BOOL=ON \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit" \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_ENABLE_CXX11:BOOL=ON \
    -D Trilinos_ENABLE_DataTransferKit:BOOL=ON \
    -D Trilinos_ENABLE_DataTransferKitC_API:BOOL=OFF \
    -D Trilinos_ENABLE_DataTransferKitFortran_API:BOOL=OFF \
    -D Trilinos_ENABLE_DataTransferKitSTKMeshAdapters:BOOL=OFF \
    -D Trilinos_ENABLE_DataTransferKitMoabAdapters:BOOL=OFF \
    -D Trilinos_ENABLE_DataTransferKitLibmeshAdapters:BOOL=OFF \
    -D Trilinos_ENABLE_DataTransferKitClassicDTKAdapters:BOOL=OFF \
    -D Trilinos_ENABLE_OpenMP:BOOL=ON \
    -D Kokkos_ENABLE_Cuda:BOOL=ON \
    -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
    -D Tpetra_INST_SERIAL:BOOL=ON \
    -D Tpetra_INST_OPENMP:BOOL=ON \
    -D Tpetra_INST_CUDA:BOOL=ON \
    -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
    -D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
    -D Tpetra_INST_INT_LONG_LONG:BOOL=OFF \
    -D Tpetra_INST_INT_INT:BOOL=OFF \
    -D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON \
    -D DataTransferKit_ENABLE_DBC:BOOL=ON \
    -D DataTransferKit_ENABLE_TESTS:BOOL=ON \
    -D DataTransferKit_ENABLE_EXAMPLES:BOOL=ON \
    -D DataTransferKit_ENABLE_ClangFormat:BOOL=ON \
    $EXTRA_ARGS \
    /home/uy7/software/Trilinos
