
SET(LIB_REQUIRED_DEP_PACKAGES
  DataTransferKitNanoflann
  DataTransferKitUtils
  DataTransferKitInterface
  Teuchos 
  Tpetra
  ThyraCore
  ThyraTpetraAdapters
 )

SET(LIB_OPTIONAL_DEP_PACKAGES)

SET(TEST_REQUIRED_DEP_PACKAGES)

SET(TEST_OPTIONAL_DEP_PACKAGES)

SET(LIB_REQUIRED_DEP_TPLS)

SET(LIB_OPTIONAL_DEP_TPLS)

SET(TEST_REQUIRED_DEP_TPLS)

SET(TEST_OPTIONAL_DEP_TPLS)
