TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
  DataTransferKitInterface
  DataTransferKitSearch
  DataTransferKitUtils
  Intrepid2
  Kokkos
  Shards
  Teuchos
  Tpetra
  TEST_REQUIRED_PACKAGES
  DataTransferKitInterface
  )
