TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitInterface
    Teuchos
    Tpetra
  TEST_REQUIRED_PACKAGES
    DataTransferKitOperators
  TEST_OPTIONAL_PACKAGES
    DataTransferKitMoabAdapters
  LIB_REQUIRED_TPLS
    MPI
    Libmesh
  )
