SET(REQUIRED_ENV_VARIABLES
TRILINOS_SOURCE_DIR
TRILINOS_BUILD_DIR
DTK_BUILD_TYPE
DTK_SOURCE_DIR
)
FOREACH(VAR ${REQUIRED_ENV_VARIABLES})
IF(NOT DEFINED ENV{${VAR}})
MESSAGE(FATAL_ERROR "Undefined ${VAR} environment variable")
ENDIF()
ENDFOREACH()

SET(CTEST_PROJECT_NAME "DTK")
SET(CTEST_NIGHTLY_START_TIME "21:00:00 EST")
SET(CTEST_CUSTOM_MAXIMUM_NUMBER_OF_ERRORS 500)
SET(CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS 500)

SET(CTEST_SOURCE_DIRECTORY "$ENV{TRILINOS_SOURCE_DIR}")
SET(CTEST_BINARY_DIRECTORY "$ENV{TRILINOS_BUILD_DIR}")
#SET(CTEST_UPDATE_COMMAND "$ENV{DTK_SOURCE_DIR}/cmake/cdash_gitpull.sh")
SET(CTEST_UPDATE_COMMAND "")
SET(CTEST_CONFIGURE_COMMAND "$ENV{DTK_SOURCE_DIR}/cmake/cdash_configure.sh")
SET(CTEST_BUILD_COMMAND "make -j8")

EXEC_PROGRAM("hostname" ARGS OUTPUT_VARIABLE HOSTNAME)
SET(CTEST_SITE ${HOSTNAME})
SET(CTEST_BUILD_NAME "DTK-$ENV{DTK_BUILD_TYPE}")

FILE(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt")

CTEST_START("Nightly")
CTEST_UPDATE()
CTEST_CONFIGURE()
CTEST_BUILD()
CTEST_TEST()

SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "qdi-imac.ornl.gov")
SET(CTEST_DROP_LOCATION "/~qdi/CDash/submit.php?project=DTK")
SET(CTEST_DROP_SITE_CDASH TRUE)
CTEST_SUBMIT()

MESSAGE("DONE")
