SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
  nanoflann  packages/nanoflann  SS  REQUIRED
  Utils      packages/Utils      SS  REQUIRED
  PointCloud packages/PointCloud SS  OPTIONAL
)

SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
